version: '3.8'

services:
  chess-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app          # mounts your entire project folder
      - /usr/src/app/node_modules # avoids overwriting node_modules inside container
    environment:
      - NODE_ENV=development
